version: "3.8"

services:
  php:
    image: wodby/php:8.4-dev-4.59.3
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    depends_on:
      - php

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
